spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://goeasy-db.clvgcrbhh40l.ap-northeast-2.rds.amazonaws.com/pansoriDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: admin
#    password: rhdlwl123!
#    url: jdbc:mysql://127.0.0.1:3306/PansoriDB?serverTimezone=UTC&characterEncoding=UTF-8
#    password: Goeasy1234!
#    username: goeasy
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/pansoriDB
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  jwt:
    secret-key: 834D9988C9EDBD5F213EAFD25641223768A853C53F2368FDFB481A69A4

  mail:
    host: smtp.naver.com
    port: 587
    username: olzlgur@naver.com
    password: s05280528
    properties:
      mail:
        smtp:
          starttls:
            enable: true
#            required: true
#          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#elasticsearch:
#  host: 127.0.0.1
#  port: 9200