spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://goeasy-db.clvgcrbhh40l.ap-northeast-2.rds.amazonaws.com/pansoriDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: rhdlwl123!
#    url: jdbc:mysql://127.0.0.1:3306/PansoriDB?serverTimezone=UTC&characterEncoding=UTF-8
#    username: goeasy
#    password: Goeasy1234!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret-key: Goeasy1234!

  mail:
    host: smtp.naver.com
    port: 587
    username: olzlgur@naver.com
    password: s05280528
    properties:
      mail:
        smtp:
          starttls:
            enable: true
#            required: true
#          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#elasticsearch:
#  host: 127.0.0.1
#  port: 9200