spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://goeasy-db.clvgcrbhh40l.ap-northeast-2.rds.amazonaws.com/pansoriDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: admin
    password: rhdlwl123!
#    url: jdbc:mysql://127.0.0.1:3306/PansoriDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    password: Goeasy1234!
#    username: goeasy
#    url: jdbc:mysql://127.0.0.1:3306/PansoriDB?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret-key: 834D9988C9EDBD5F213EAFD25641223768A853C53F2368FDFB481A69A4

  mail:
    host: smtp.naver.com
    port: 587
    username: olzlgur@naver.com
    password: s05280528
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

cloud:
  aws:
    s3:
      bucket: pansori.s3.bucket
    credentials:
      access-key: AKIASKTFCHJXTQXTVPWA
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 10000

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR